# -*- coding: utf-8 -*-
"""Extração de dados Michael Jordan, LeBron James e Luka Doncic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/128AV8Gwsx4Cy-_rg_GWsENo4fMAWnU0k
"""

import pandas as pd
import requests

pip install numpy==1.24.2

pip install nba_api

from nba_api.stats.endpoints import playercareerstats, teamvsplayer
from nba_api.stats.static import players, teams

nba_players = players.get_players()

jogadores_nomes = pd.DataFrame(nba_players)
jogadores_nomes.head()

lista_nomes = [ccccc]

lista = []
for jogador in lista_nomes:
  jogador_id = jogadores_nomes.query("full_name == @jogador")
  lista.append(jogador_id)

jogador_id = pd.concat(lista)
jogador_id.head()

id = list(jogador_id['id'])

print(id)

jogadores = []

for jogador in id:
  players = playercareerstats.PlayerCareerStats(player_id=jogador)
  players = players.get_data_frames()[0]
  player_data = pd.DataFrame(players)
  jogadores.append(players)

jogadores = pd.concat(jogadores)

jogadores.head(3)

dict_jogadores = {
    893 :'Michael Jordan',
    2544 :'LeBron James',
    1629029 :'Luka Doncic'
}

jogadores.dtypes

jogadores['JOGADOR'] = jogadores['PLAYER_ID'].map(dict_jogadores)

jogadores.head(3)

jogadores.to_csv('comparativo_geracoes_nba', sep=',', index=False)

